lettings/urls.py
from django.urls import path

from . import views

app_name = "lettings"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:letting_id>/", views.letting, name="letting"),
]

oc_lettings_site/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("lettings/", include("lettings.urls", namespace="lettings")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("admin/", admin.site.urls),
]


def trigger_error(request) -> None:
    """For sentry test"""
    division_by_zero = 1 / 0


urlpatterns += [
    path("sentry-debug/", trigger_error),
    # ...
]

profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:username>/", views.profile, name="profile"),
]

lettings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinLengthValidator


class Address(models.Model):
    number = models.PositiveIntegerField(validators=[MaxValueValidator(9999)])
    street = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    state = models.CharField(max_length=2, validators=[MinLengthValidator(2)])
    zip_code = models.PositiveIntegerField(validators=[MaxValueValidator(99999)])
    country_iso_code = models.CharField(
        max_length=3, validators=[MinLengthValidator(3)]
    )

    class Meta:
        verbose_name_plural = "Addresses"

    def __str__(self):
        return f"{self.number} {self.street}"


class Letting(models.Model):
    title = models.CharField(max_length=256)
    address = models.OneToOneField(Address, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user")
    favorite_city = models.CharField(max_length=64, blank=True)

    def __str__(self):
        return self.user.username

lettings/views.py
from django.shortcuts import render

from .models import Letting


# Aenean leo magna, vestibulum et tincidunt fermentum, consectetur quis velit.
# Sed non placerat massa. Integer est nunc, pulvinar a tempor et, bibendum id
# arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
# posuere cubilia curae; Cras eget scelerisque
def index(request):
    lettings_list = Letting.objects.all()
    context = {"lettings_list": lettings_list}
    return render(request, "lettings/index.html", context)


# Cras ultricies dignissim purus, vitae hendrerit ex varius non. In accumsan
# porta nisl id eleifend. Praesent dignissim, odio eu consequat pretium, purus
# urna vulputate arcu, vitae efficitur lacus justo nec purus. Aenean finibus
# faucibus lectus at porta. Maecenas auctor, est ut luctus congue, dui enim
# mattis enim, ac condimentum velit libero in magna. Suspendisse potenti. In
# tempus a nisi sed laoreet. Suspendisse porta dui eget sem accumsan interdum.
# Ut quis urna pellentesque justo mattis ullamcorper ac non tellus. In
# tristique mauris eu velit fermentum, tempus pharetra est luctus. Vivamus
# consequat aliquam libero, eget bibendum lorem. Sed non dolor risus. Mauris
# condimentum auctor elementum. Donec quis nisi ligula. Integer vehicula
# tincidunt enim, ac lacinia augue pulvinar sit amet.
def letting(request, letting_id):
    letting = Letting.objects.get(id=letting_id)
    context = {
        "title": letting.title,
        "address": letting.address,
    }
    return render(request, "lettings/letting.html", context)

oc_lettings_site/views.py
from django.shortcuts import render


# Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque molestie quam
# lobortis leo consectetur ullamcorper non id est. Praesent dictum,
# nulla eget feugiat sagittis, sem mi convallis eros,
# vitae dapibus nisi lorem dapibus sem. Maecenas pharetra purus ipsum, eget
# consequat ipsum lobortis quis. Phasellus eleifend ex auctor venenatis tempus.
# Aliquam vitae erat ac orci placerat luctus. Nullam elementum urna nisi,
# pellentesque iaculis enim cursus in. Praesent volutpat porttitor magna, non
# finibus neque cursus id.
def index(request):
    return render(request, "index.html")

profiles/views.py
from django.shortcuts import render

from .models import Profile


# Sed placerat quam in pulvinar commodo. Nullam laoreet consectetur ex, sed
# consequat libero pulvinar eget. Fusc faucibus, urna quis auctor pharetra,
# massa dolor cursus neque, quis dictum lacus d
def index(request):
    profiles_list = Profile.objects.all()
    context = {"profiles_list": profiles_list}
    return render(request, "profiles/index.html", context)


# Aliquam sed metus eget nisi tincidunt ornare accumsan eget lac
# laoreet neque quis, pellentesque dui. Nullam facilisis pharetra vulputate.
# Sed tincidunt, dolor id facilisis fringilla, eros leo tristique lacus,
# it. Nam aliquam dignissim congue. Pellentesque habitant morbi tristique
# senectus et netus et males
def profile(request, username):
    profile = Profile.objects.get(user__username=username)
    context = {"profile": profile}
    return render(request, "profiles/profile.html", context)

lettings/templates/lettings/index.html
{%extends "base.html"%}

{% block title %}Lettings{% endblock %}


{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col">
            <h1>Lettings</h1>
        </div>           
    </div>
    <div class="row">
        <div class="col">
            {% if lettings_list %}
                <ul  class="list-group">
                {% for letting in lettings_list %}
                    <li class="list-group-item">
                        <a href="{% url 'lettings:letting' letting_id=letting.id %}">
                            {{ letting.title }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No lettings are available.</p>
            {% endif %}
        </div>
    </div>
    <div class="row container text-center">
        <div class="col">
            <a href="{% url 'index' %}">Home</a> |
            <a href="{% url 'profiles:index' %}">Profiles</a>
        </div>
    </div>
{% endblock %}

lettings/templates/lettings/letting.html
{%extends "base.html"%}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <div class="container text-center">
        <div class="row">
            <div class="col">
                <h1>{{ title }}</h1>
            </div>
        </div>
    </div>

    <div class="container jumbotron">
        <div class="row">
            <div class="col">        
                <p>{{ address.number }} {{ address.street }}</p>
                <p>{{ address.city }}, {{ address.state }} {{ address.zip_code }}</p>
                <p>{{ address.country_iso_code }}</p>
            </div>
        </div>
    </div>
    <div class="container text-center">
        <div class="row">
            <div class="col">
                <a href="{% url 'lettings:index' %}">Back</a> |
                <a href="{% url 'index' %}">Home</a> |
                <a href="{% url 'profiles:index' %}">Profiles</a>
            </div>
        </div>
    </div>

{% endblock %}

profiles/templates/profiles/index.html
{%extends "base.html"%}

{% block title %}Profiles{% endblock %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col">
            <h1>Profiles</h1>
        </div>           
    </div>
    <div class="row">
        <div class="col">
            {% if profiles_list %}
                <ul class="list-group">
                {% for profile in profiles_list %}
                    <li class="list-group-item">
                        <a href="{% url 'profiles:profile' username=profile.user.username %}">
                            {{ profile.user.username }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No profiles are available.</p>
            {% endif %}
        </div>
    </div>
    <div class="row container text-center">
        <div class="col">
            <a href="{% url 'index' %}">Home</a> |
            <a href="{% url 'lettings:index' %}">Lettings</a>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/profile.html
{%extends "base.html"%}

{% block title %}{{ profile.user.username }}{% endblock %}

{% block content %}

    <div class="container text-center">
        <div class="row">
            <div class="col">
                <h1>{{ profile.user.username }}</h1>
            </div>
        </div>
    </div>

    <div class="container jumbotron">
        <div class="row">
            <div class="col">        
                <p><span class='first-txt-light'>First name:</span> {{ profile.user.first_name }}</p>
                <p><span class='first-txt-light'>Last name:</span>  {{ profile.user.last_name }}</p>
                <p><span class='first-txt-light'>Email:</span>  {{ profile.user.email }}</p>
                <p><span class='first-txt-light'>Favorite city:</span>  {{ profile.favorite_city }}</p>
            </div>
        </div>
    </div>
    <div class="container text-center">
        <div class="row">
            <div class="col">
                <a href="{% url 'profiles:index' %}">Back</a> |
                <a href="{% url 'index' %}">Home</a> |
                <a href="{% url 'lettings:index' %}">Lettings</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}main global template{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" id='logo'>

    </head>

    <body>

        <header class="first-bg-light sticky-top">
            <div class="container">
                <div class="row">
                    <nav class="col navbar navbar-expand-lg">                            
                        <img id="logo" src="{% static 'img/logo_trsp.png' %}" alt="logo"> </img>
                        <h1>Holiday Homes</h1>
                    </nav>
                </div>       
            </div>
        </header>
            
        {% block content %}
        {% endblock %}
        
    </body>
</html>

templates/index.html
{%extends "base.html"%}

{% block title %}Holiday Homes{% endblock %}

{% block content %}
<div class="container text-center">
    <div class="row">
        <div class="col">
            <h1>Welcome to Holiday Homes</h1>
        </div>           
    </div>
        <div class="row">
            <div class="col">
                <a href="{% url 'profiles:index' %}">Profiles</a> |
                <a href="{% url 'lettings:index' %}">Lettings</a>
            </div>           
        </div>
    </div>
   
{% endblock %}